Add polkadex fungible assets
Polkadex-Substrate/Polkadex pull request #146
Opened 2021-03-26 13:19 UTC by ksr30

2021-03-27 13:54 UTC, Gauthamastro requested changes

2021-03-27 13:54 UTC, Gauthamastro commented on pallets/Polkadex_Fungible_Assets/src/lib.rs
> +    pub fn transfer_native(
Why do we need this function?

2021-03-27 13:54 UTC, Gauthamastro commented on pallets/Polkadex_Fungible_Assets/src/lib.rs
> +
We need one more dispatchable functions for claiming the vested tokens

fn claim( vestingID): something like this, We need to identify each vesting using some identifiers

2021-03-27 13:54 UTC, Gauthamastro commented on pallets/Polkadex_Fungible_Assets/src/lib.rs
> +//		    orml_currencies::NativeCurrencyOf::<T>::transfer(&who, &tresury_account, amout_to_trasfer);
orml_currencies's transfer_native function here

2021-03-27 13:54 UTC, Gauthamastro commented on pallets/Polkadex_Fungible_Assets/src/lib.rs
> +
Add GPL v3 license and a copyright notice here

2021-03-27 13:54 UTC, Gauthamastro commented on pallets/Polkadex_Fungible_Assets/src/lib.rs
> +            ensure!(<InfoAsset<T>>::contains_key(&asset_id), <Error<T>>::AssetIdNotExists);
Ensure the vectors of metadata are bounded.

2021-03-27 13:54 UTC, Gauthamastro commented on primitives/src/lib.rs
> +pub mod engine;
Remove engine, and delete engine file

2021-03-27 13:54 UTC, Gauthamastro commented on runtime/src/lib.rs
> +        PolkadexFungibleAssets: polkadex_fungible_assets::{Module, Call, Event<T>},
PolkadexFungibleAssets should be coming after Tokens and Currencies pallet

2021-04-01 07:16 UTC, ayushmishra2005 commented on pallets/Polkadex_Fungible_Assets/src/lib.rs
> +    pub fn transfer_native(
@ksr30

2021-04-03 06:23 UTC, Gauthamastro approved these changes

2021-04-03 06:23 UTC, merged