Feature/token faucet
Polkadex-Substrate/Polkadex pull request #172
Opened 2021-05-05 12:35 UTC by mambisi

2021-05-13 04:52 UTC, Gauthamastro requested changes
@mambisi Please update this branch with changes from develop.

2021-05-13 04:59 UTC, ayushmishra2005 commented on pallets/ocex/Cargo.toml
> +timestamp= {git = "https://github.com/paritytech/substrate.git", package = "pallet-timestamp", version = "3.0.0", default-features = false}
We can remove this.

2021-05-13 11:40 UTC, mambisi commented on pallets/ocex/Cargo.toml
> +timestamp= {git = "https://github.com/paritytech/substrate.git", package = "pallet-timestamp", version = "3.0.0", default-features = false}
Ohk

2021-05-18 13:08 UTC, Gauthamastro approved these changes

2021-05-18 13:08 UTC, merged