Added account id and Signature in primitives
Polkadex-Substrate/Polkadex pull request #178
Opened 2021-05-14 08:12 UTC by ksr30

2021-05-14 08:17 UTC, Gauthamastro requested changes

2021-05-14 08:17 UTC, Gauthamastro commented on primitives/src/assets.rs
> +use sp_runtime::{
Please remove these extra imports

2021-05-14 08:26 UTC, ksr30 commented on primitives/src/assets.rs
> +use sp_runtime::{
done

2021-05-15 09:38 UTC, Gauthamastro requested changes

2021-05-15 09:38 UTC, Gauthamastro commented on primitives/src/assets.rs
> +}};
Move to a different file

2021-05-15 10:07 UTC, Gauthamastro approved these changes

2021-05-15 12:12 UTC, Gauthamastro approved these changes

2021-05-15 12:12 UTC, merged