Fix removes duplicate primitive mods
Polkadex-Substrate/Polkadex pull request #198
Opened 2021-06-10 19:30 UTC by mambisi

Resolves #192

2021-06-11 03:32 UTC, Gauthamastro requested changes

2021-06-11 03:32 UTC, Gauthamastro commented on node/Cargo.toml
> +polkadex-primitives = { git = "https://github.com/Polkadex-Substrate/Polkadex.git", branch = 'develop', default-features = false }
@mambisi Please use a local path here

2021-06-11 03:32 UTC, Gauthamastro commented on pallets/fungible-assets/Cargo.toml
> +polkadex-primitives = { git = "https://github.com/Polkadex-Substrate/Polkadex.git", branch = 'develop', default-features = false }
^^^^

2021-06-11 03:32 UTC, Gauthamastro commented on primitives/src/lib.rs
> +// you may not use this file except in compliance with the License.
Why is Parity's License here?

2021-06-11 03:33 UTC, Gauthamastro commented
CI is failing too

2021-06-14 08:32 UTC, mambisi commented on node/Cargo.toml
> +polkadex-primitives = { git = "https://github.com/Polkadex-Substrate/Polkadex.git", branch = 'develop', default-features = false }
fixed in latest change

2021-06-14 08:32 UTC, mambisi commented on pallets/fungible-assets/Cargo.toml
> +polkadex-primitives = { git = "https://github.com/Polkadex-Substrate/Polkadex.git", branch = 'develop', default-features = false }
Ok

2021-06-14 08:32 UTC, mambisi commented on primitives/src/lib.rs
> +// you may not use this file except in compliance with the License.
ok removed

2021-06-14 11:17 UTC, ksr30 commented
@Gauthamastro can we merge it?

2021-06-14 12:05 UTC, Gauthamastro approved these changes

2021-06-14 12:06 UTC, merged