Feature Random Participants
Polkadex-Substrate/Polkadex pull request #255
Opened 2021-07-26 12:25 UTC by mambisi

resolves #224 #245 #246

Random Participants,
Motivation for the Algorithm
Algorithm R : https://en.wikipedia.org/wiki/Reservoir_sampling
Participant slots are filled, slot capacity is calculated by max_allocation divided by total amount, then new participants are are placed in random slots

2021-07-28 21:03 UTC, mambisi commented
@Gauthamastro  Please take a look a this PR

2021-08-03 09:36 UTC, simonsso requested changes
This was done over a voice call with the developer.

2021-08-03 09:36 UTC, simonsso commented on pallets/Polkadex_Ido/src/lib.rs
> +
no longer needed remove

2021-08-03 09:36 UTC, simonsso commented on pallets/Polkadex_Ido/src/lib.rs
> +                let total_potential_raise : T::Balance = interested_participants.iter()
todo: add ticket for technical dept here. This algo is inefficient

2021-08-03 09:36 UTC, simonsso commented on pallets/Polkadex_Ido/src/test.rs
> +    let balance: Balance = 500;
add comments describing the test scenario here.

2021-08-03 09:36 UTC, simonsso commented on pallets/Polkadex_Ido/src/test.rs
> +            PolkadexIdo::register_round(
description here too.

2021-08-03 09:36 UTC, simonsso commented on pallets/ocex/src/lib.rs
> +        <MainAccounts<T>>::try_mutate(main, |ref mut linked_account: &mut LinkedAccount<T>| {
auto format move to another pr

2021-08-05 10:25 UTC, simonsso requested changes
Sanitize input and array lengths

2021-08-05 10:25 UTC, simonsso commented on contracts/uniswap_v2/lib.rs
> +                i += 1;
rewrite the loop without the mutable index `i`

!ensure path.len() == amounts.len()

2021-08-05 10:25 UTC, simonsso commented on contracts/uniswap_v2/lib.rs
> +            }
If len == 0...

2021-08-05 10:25 UTC, simonsso commented on contracts/uniswap_v2/lib.rs
> +
size check

2021-08-05 10:25 UTC, simonsso commented on contracts/uniswap_v2/lib.rs
> +        }
please explain this part.

2021-08-05 10:25 UTC, simonsso commented on contracts/uniswap_v2/lib.rs
> +                .map(|amounts| amounts[0])
explain what this is doing

2021-08-05 10:25 UTC, simonsso commented on pallets/Polkadex_Ido/src/test.rs
> +    // Amount to Raise for funding round
Overview of test case in comment, no need to duplicate every assignment with an identical comment - give the big picture in a few lines

2021-08-05 11:12 UTC, simonsso commented
Copy files and make a new branch from develop

2021-08-05 11:12 UTC, closed without merging