Sr labs audit ido pallet week2
Polkadex-Substrate/Polkadex pull request #262
Opened 2021-07-29 10:42 UTC by mambisi

Branched from #224 
Resolves #248

2021-08-03 06:20 UTC, simonsso requested changes
Please describe in the PR what is changed and why.

(it makes it easier for a reviewer to understand what we are looking at and what problem it is solving)

2021-08-03 06:30 UTC, simonsso requested changes
Where is this cleaning up storage bloat and what review comments is it solving?

2021-08-03 06:49 UTC, mambisi commented on pallets/Polkadex_Ido/src/lib.rs
> +            // Clean up WhiteListInvestors and InterestedParticipants in all expired rounds
@simonsso  It cleans up expired funding rounds when a new block is created

2021-08-12 01:39 UTC, simonsso commented
This branch is obsoleted

2021-08-12 01:39 UTC, closed without merging