Uniswap v2 ink! smart contract
Polkadex-Substrate/Polkadex pull request #266
Opened 2021-07-30 12:51 UTC by frankli-dev

2021-08-03 05:13 UTC, simonsso requested changes
Please increase test coverage, a test case with all code commented out is not adding any value to anyone.

2021-08-03 05:13 UTC, simonsso commented on contracts/uniswap_v2/lib.rs
> +                    Option::Some(p) => *p,
I prefer `Some()` over `Option::Some()`

2021-08-03 05:13 UTC, simonsso commented on contracts/uniswap_v2/lib.rs
> +            // struct MockedExtension;
This test case is totally useless.

2021-08-04 15:19 UTC, frankli-dev commented on contracts/uniswap_v2/lib.rs
> +            self.do_deposit_dex_share(caller, &trading_pair, share_increment)?;
tested!

2021-08-04 23:26 UTC, simonsso approved these changes

2021-08-05 00:53 UTC, merged