Feature Random Participants
Polkadex-Substrate/Polkadex pull request #279
Opened 2021-08-05 11:54 UTC by mambisi

resolves #224

2021-08-06 01:28 UTC, simonsso requested changes

2021-08-06 01:28 UTC, simonsso commented on pallets/Polkadex_Ido/src/lib.rs
> +        <Nonce>::put(current_nonce.saturating_add(1));
A saturating add here will at some point always return the same value which defeats the presuppose of the nonce.
a wrap around is better for this kind of calculations.

2021-08-09 05:41 UTC, mambisi commented
Also resolves #245

2021-08-10 08:24 UTC, simonsso approved these changes

2021-08-11 06:24 UTC, simonsso commented on pallets/Polkadex_Ido/src/lib.rs
> +        <Nonce>::put(current_nonce + 1);
wrapping add here

2021-08-12 00:15 UTC, simonsso approved these changes

2021-08-12 01:37 UTC, merged