Update run-a-validator.md
Polkadex-Substrate/Polkadex pull request #427
Opened 2022-06-06 06:52 UTC by gabaod

update to latest version 1.0.8

2022-06-08 11:05 UTC, zktony commented
LGTM

2022-06-08 11:05 UTC, zktony approved these changes

2022-06-08 14:30 UTC, felixfaisal approved these changes

2022-06-21 07:57 UTC, 35359595 commented
please replace links with `latest` like this:
`https://github.com/Polkadex-Substrate/Polkadex/releases/latest/download/customSpecRaw.json`

2022-06-21 07:57 UTC, 35359595 requested changes
Make all links point to `latest` release.

2022-06-22 15:52 UTC, closed without merging