Integrate OCEX pallet to runtime
Polkadex-Substrate/Polkadex pull request #434
Opened 2022-06-08 10:00 UTC by felixfaisal

This PR adds and integrates the OCEX pallet to the runtime

2022-06-08 10:37 UTC, zktony requested changes

2022-06-08 10:37 UTC, zktony commented on pallets/ocex/src/benchmarking.rs
> +// This file is part of Substrate.
Please update the copyright.

2022-06-08 10:37 UTC, zktony commented on pallets/ocex/src/benchmarking.rs
> +//
please remove these comments

2022-06-08 10:37 UTC, zktony commented on pallets/ocex/src/benchmarking.rs
> +	//   `cargo test -p pallet-example-basic --all-features`, you will see one line per case:
same

2022-06-08 10:37 UTC, zktony commented on pallets/ocex/src/benchmarking.rs
> +	set_dummy_benchmark {
These benchmarks are for example pallet.

2022-06-08 10:37 UTC, zktony commented on pallets/ocex/src/tests.rs
> +// Copyright (C) 2019-2022 Parity Technologies (UK) Ltd.
Copyright

2022-06-08 13:38 UTC, zktony commented on pallets/ocex/src/benchmarking.rs
> +	set_dummy_benchmark {
will be handled in #435

2022-06-08 13:39 UTC, zktony approved these changes

2022-06-09 01:32 UTC, Gauthamastro approved these changes

2022-06-09 05:23 UTC, merged