Implement register_investor extrinsic
Polkadex-Substrate/Polkadex pull request #476
Opened 2022-07-25 06:49 UTC by felixfaisal

This PR implements the register_investor extrinsic that will reserve PDEX from an investor

2022-07-25 22:06 UTC, serhii-temchenko requested changes

2022-07-25 22:06 UTC, serhii-temchenko commented on pallets/polkadex-ido/src/lib.rs
> +		/// * `origin`: Account to be registered as Investor
Before you told that `origin` is property which present in all extrinsicses, but now it's here. Please be consistent. If it's not needed (IMO with it it's more common and better) - remove everywhere, if it's needed - add everywhere.

2022-07-25 22:06 UTC, serhii-temchenko commented on pallets/polkadex-ido/src/lib.rs
> +		pub fn register_investor(origin: OriginFor<T>) -> DispatchResult {
In IDO documentation in notion name is different, please update one side...

2022-07-25 22:06 UTC, serhii-temchenko commented on pallets/polkadex-ido/src/lib.rs
> +            // TODO: We are reserving for default 100 blocks, This must be discussed
Where/when this must be discussed? Please discuss those questions before moving to `ReadyForReview` status.

2022-07-25 22:06 UTC, serhii-temchenko commented on pallets/polkadex-ido/src/lib.rs
> +	pub(super) type InfoInvestor<T: Config> = StorageMap<_, Blake2_128Concat, T::AccountId, InvestorLockData<T>, OptionQuery>;
Should be saved invested amount?

2022-07-30 02:51 UTC, Gauthamastro requested changes

2022-07-30 02:51 UTC, Gauthamastro commented on pallets/polkadex-ido/src/lib.rs
> +            // TODO: We are reserving for default 100 blocks, This must be discussed
There is no time limit for reserving for IDO; it will be reserved until the Investor deregisters.

2022-09-29 05:25 UTC, closed without merging