Impl delay for withdrawals above a certain limit
Polkadex-Substrate/Polkadex pull request #490
Opened 2022-08-24 06:33 UTC by zktony

Impl delay for withdrawals above a certain limit.

2022-08-24 11:10 UTC, Gauthamastro commented
@zktony An attacker can make multiple smaller withdrawals just below the limit and use a batch execution of them, to circumvent this guard, so having the delay for all withdrawals is better. Also, one might say, there is a front-running scenario there but I believe that is not the case for withdrawals to Ethereum and we should give priority to securing the user funds and protecting them with governance.

2022-08-24 11:18 UTC, Gauthamastro requested changes
CHeck my comment above

2022-08-25 10:57 UTC, Gauthamastro reviewed
- [ ] Needs unit testing 
- [ ] benchmarking

2022-08-25 10:57 UTC, Gauthamastro commented on pallets/asset-handler/src/lib.rs
> +
Do this ensure before fee calculation

2022-08-26 07:36 UTC, zktony commented on pallets/asset-handler/src/lib.rs
> +
done

2022-08-26 07:39 UTC, Gauthamastro requested changes

2022-08-26 07:39 UTC, Gauthamastro commented on pallets/asset-handler/src/lib.rs
> +					).expect("Chainbridge::transfer_fungible failed");
Can't have this.

2022-08-26 07:44 UTC, zktony commented on pallets/asset-handler/src/lib.rs
> +					).expect("Chainbridge::transfer_fungible failed");
removed

2022-08-26 09:21 UTC, Gauthamastro requested changes

2022-08-26 09:21 UTC, Gauthamastro commented on pallets/asset-handler/src/lib.rs
> +					);
Handle the result

2022-08-26 09:58 UTC, zktony commented on pallets/asset-handler/src/lib.rs
> +					);
done

2022-08-27 10:39 UTC, serhii-temchenko approved these changes

2022-08-29 02:43 UTC, Gauthamastro approved these changes

2022-08-29 02:43 UTC, merged