Refactor Withdrawals
Polkadex-Substrate/Polkadex pull request #497
Opened 2022-08-26 17:47 UTC by felixfaisal

This PR resolves #496

2022-08-27 07:02 UTC, Gauthamastro requested changes

2022-08-27 07:02 UTC, Gauthamastro commented on pallets/ocex/src/lib.rs
> +		OnchainEventsFilled,
Add docs

2022-08-27 07:02 UTC, Gauthamastro commented on pallets/ocex/src/lib.rs
>  			0
Benchmarks

2022-08-27 07:02 UTC, Gauthamastro commented on pallets/ocex/src/lib.rs
> +	// TODO: No longer needed
Remove if not required

2022-08-27 11:02 UTC, serhii-temchenko requested changes
No benchmarks and tests. Please follow and resolve all points in issue #496 which suppose to be closed by this pr.

2022-08-27 11:02 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> -
In issue (#496) which will be closed by merging this PR nothing about this... why is this removed? no info in description about this. How am I suppose to review this without context? Please update description about this change...

2022-08-27 11:02 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
>  			0
plus update issue with checking points which was resolved and which not...

2022-08-27 11:02 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +			}).is_ok(), Error::<T>::OnchainEventsFilled);
Typo in `OnchainEventsFilled` it suppose to be `failed`?

2022-08-27 11:02 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +			}).is_ok(), Error::<T>::OnchainEventsFilled);
Why is everything wrapped in `ensure`? is `<Withdrawals<T>>::insert` or `<FeesCollected<T>>::insert` or other inserts can fail? I don't see this in a signature. If not, please move it out of assertion, it's confusing and make no sense.

2022-08-29 02:58 UTC, felixfaisal commented on pallets/ocex/src/lib.rs
> +			}).is_ok(), Error::<T>::OnchainEventsFilled);
It means to say the vector is full

2022-08-29 03:41 UTC, felixfaisal commented on pallets/ocex/src/lib.rs
> -
This was accidentally removed, Sorry about that, I have updated it ✅

2022-08-29 04:23 UTC, felixfaisal commented on pallets/ocex/src/lib.rs
> +		OnchainEventsFilled,
Updated ✅

2022-08-29 06:23 UTC, felixfaisal commented on pallets/ocex/src/lib.rs
> +	// TODO: No longer needed
Removed ✅

2022-08-29 06:23 UTC, felixfaisal commented on pallets/ocex/src/lib.rs
> +			}).is_ok(), Error::<T>::OnchainEventsFilled);
@Gauthamastro can you comment on this

2022-08-29 06:39 UTC, felixfaisal commented on pallets/ocex/src/lib.rs
> +			}).is_ok(), Error::<T>::OnchainEventsFilled);
Removed outside ensure macro ✅

2022-08-29 06:42 UTC, Gauthamastro reviewed
Needs Error to be renamed

2022-08-29 07:19 UTC, Gauthamastro approved these changes

2022-08-29 07:20 UTC, Gauthamastro requested changes

2022-08-29 07:20 UTC, Gauthamastro commented on pallets/ocex/src/lib.rs
>  			0
Benchmark this too.

2022-08-29 07:26 UTC, felixfaisal commented on pallets/ocex/src/lib.rs
>  			0
Resolved ✅

2022-08-29 07:26 UTC, felixfaisal commented on pallets/ocex/src/lib.rs
>  			0
Updated ✅

2022-08-29 08:13 UTC, Gauthamastro approved these changes

2022-08-29 08:31 UTC, serhii-temchenko approved these changes

2022-08-29 08:31 UTC, merged