fix: add if condition for withdrawals onchain events
Polkadex-Substrate/Polkadex pull request #500
Opened 2022-08-29 11:31 UTC by felixfaisal

This includes an `If` condition to not fill onchain events when a snapshot has empty withdrawals

2022-08-29 19:43 UTC, serhii-temchenko commented
@felixfaisal build is failing. I assume you need to update primitives repo.

2022-09-20 20:09 UTC, serhii-temchenko requested changes
I think the same issue as [here](https://github.com/Polkadex-Substrate/Polkadex/pull/510#pullrequestreview-1096804416)?

2022-09-22 06:34 UTC, serhii-temchenko approved these changes

2022-09-27 12:26 UTC, Gauthamastro approved these changes

2022-09-27 12:26 UTC, merged