[428] Improve CI/CD
Polkadex-Substrate/Polkadex pull request #506
Opened 2022-09-01 06:21 UTC by serhii-temchenko

- [ ] Check for rustfmt format
- [ ] Check for any warnings 
- [ ] Check for any clippy warnings 
- [ ] Check for any unused dependencies 
- [ ] Check for code coverage and pass only if certain threshold is met.

2022-09-05 16:39 UTC, serhii-temchenko commented
CI failing tests will be resolved in issue #509.

2022-09-05 20:03 UTC, 35359595 requested changes

2022-09-05 20:03 UTC, 35359595 commented on pallets/asset-handler/src/lib.rs
> +				Self::convert_18dec_to_12dec(amount).ok_or(Error::<T>::DivisionUnderflow)?;
please revert back to `ok_or_else()` as it's lazy evaluated - less CPU per extrinsic...

2022-09-05 20:03 UTC, 35359595 commented on pallets/ocex/src/lib.rs
> +					withdrawals: withdrawal_vector.clone(),
I prefer leaving `to_owned()` instead of `clone()` as it will most likely call `clone()` for heap types, but will copy if possible or even do proper re-initialization if required.

2022-09-05 20:03 UTC, 35359595 commented on pallets/ocex/src/lib.rs
> +								withdrawal_vector.clone(),
Same with `to_owned()` vs just `clone()`

2022-09-05 20:03 UTC, 35359595 commented on pallets/ocex/src/lib.rs
> +		// TODO: Commented out for testing. Should be restored before mainnet launch
entire impl can be annotated with `#[cfg(test)]` for now?

2022-09-05 20:03 UTC, 35359595 commented on pallets/ocex/src/lib.rs
> +	type EnclaveSnapshotType<T> = EnclaveSnapshot<
put this type definition next to `WithdarawlsMap` where it should be =)

2022-09-05 20:03 UTC, 35359595 commented on pallets/ocex/src/weights.rs
> +		(908_600 as Weight)
problem here was in missing one `0` at the end, not wrong underscore - revert and add it or we have underweighted extrinsic!

2022-09-05 20:03 UTC, 35359595 commented on pallets/ocex/src/weights.rs
> +		(908_600 as Weight)
same as above - add `0` at the end!

2022-09-05 20:03 UTC, 35359595 commented on pallets/pdex-migration/src/lib.rs
> +				max_tokens: 3_172_895u128.saturating_mul(1_000_000_000_000_u128).saturated_into(),
canonical way of type annotation in integer literals is withot `_`. is there a clippy / fmt issue with it? if no - revert please

2022-09-05 20:03 UTC, 35359595 commented on pallets/polkadex-ido/src/lib.rs
> +						let investor_share = Perquintill::from_rational(
❤️‍🩹

2022-09-05 20:03 UTC, 35359595 commented on pallets/polkadex-ido/src/lib.rs
> +			let start_block = vote_end_block.saturating_add(1_u128.saturated_into());
again, canonical type literal without underscore =)

2022-09-06 02:09 UTC, serhii-temchenko commented on pallets/asset-handler/src/lib.rs
> +				Self::convert_18dec_to_12dec(amount).ok_or(Error::<T>::DivisionUnderflow)?;
This is clippy [suggestion](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_lazy_evaluations). Reverted and added allow annotation.

2022-09-06 02:11 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +					withdrawals: withdrawal_vector.clone(),
You mean replace with `withdrawal_vector.to_owned()`? Done.

2022-09-06 02:13 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +								withdrawal_vector.clone(),
Done.

2022-09-06 02:26 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +		// TODO: Commented out for testing. Should be restored before mainnet launch
This pr only includes CS and Clippy fixes, this method was unused (even in tests by author. I assume by saying "for testing" it meant to be used in manual tests or something) and on the [this](https://github.com/Polkadex-Substrate/Polkadex/blob/68c985640e74c2e14213ccbdb165970ac25f2a89/pallets/ocex/src/lib.rs#L195) line is commented a single call to this method, so I just commented it here with the same message to pass linter/fmt errors. So adding test annotation is not relevant here I assume?

2022-09-06 02:34 UTC, serhii-temchenko commented on pallets/pdex-migration/src/lib.rs
> +				max_tokens: 3_172_895u128.saturating_mul(1_000_000_000_000_u128).saturated_into(),
Yes, this is from clippy. Receiving [this](https://rust-lang.github.io/rust-clippy/master/index.html#inconsistent_digit_grouping) warning.

2022-09-06 07:42 UTC, 35359595 approved these changes
LGTM

2022-09-06 08:20 UTC, felixfaisal approved these changes

2022-09-06 08:20 UTC, merged