remove TradingPairStatus
Polkadex-Substrate/Polkadex pull request #511
Opened 2022-09-06 10:47 UTC by nuel77

The storage item TradingPairStatus has been removed , now the TradingPairConfig itself will have the operational status of the tradingPair.

2022-09-08 15:58 UTC, Gauthamastro submitted a review, later dismissed

2022-09-08 20:13 UTC, serhii-temchenko requested changes
Please fix formatter errors.

2022-09-09 13:03 UTC, Gauthamastro approved these changes, later dismissed

2022-09-09 22:53 UTC, serhii-temchenko approved these changes

2022-09-11 03:09 UTC, Gauthamastro approved these changes

2022-09-11 03:09 UTC, merged