Set Fees to default in `submit_snapshot`
Polkadex-Substrate/Polkadex pull request #513
Opened 2022-09-06 13:49 UTC by felixfaisal

This PR will set fees param to default in `submit_snapshot` to avoid duplication of data, There is a subsequent unit test for it as well

2022-09-08 15:57 UTC, Gauthamastro submitted a review, later dismissed

2022-09-08 20:05 UTC, serhii-temchenko requested changes
Please fix formatter errors.

2022-09-09 21:21 UTC, serhii-temchenko approved these changes

2022-09-11 03:13 UTC, Gauthamastro approved these changes

2022-09-11 03:13 UTC, merged