Implemented Token whitelisting for CB Pallet
Polkadex-Substrate/Polkadex pull request #523
Opened 2022-09-13 11:11 UTC by zktony

Implemented Token whitelisting for CB Pallet. Will close #477

2022-09-14 19:34 UTC, serhii-temchenko requested changes

2022-09-14 19:34 UTC, serhii-temchenko commented on pallets/ocex/src/tests.rs
> +				snapshot_hash: mmr_root,
Please update var name as well. Do we need var definition at all here? we can just remove `let mmr_root: H256 = H256::random();` and add `snapshot_hash: H256::random()`

2022-09-14 19:34 UTC, serhii-temchenko commented on pallets/ocex/src/tests.rs
> +				snapshot_hash: mmr_root,
Same.

2022-09-14 19:34 UTC, serhii-temchenko commented on pallets/ocex/src/tests.rs
> +				snapshot_hash: mmr_root,
Same

2022-09-14 19:34 UTC, serhii-temchenko commented on pallets/ocex/src/tests.rs
> +				snapshot_hash: mmr_root,
Same

2022-09-14 19:34 UTC, serhii-temchenko commented on pallets/ocex/src/tests.rs
> +				snapshot_hash: mmr_root,
Same

2022-09-14 19:34 UTC, serhii-temchenko commented on pallets/ocex/src/tests.rs
> +				snapshot_hash: mmr_root,
Same

2022-09-14 19:34 UTC, serhii-temchenko commented on pallets/ocex/src/tests.rs
> +				snapshot_hash: mmr_root,
Same

2022-09-14 19:34 UTC, serhii-temchenko commented on pallets/ocex/src/tests.rs
> +				snapshot_hash: hash,
Same

2022-09-19 19:05 UTC, serhii-temchenko requested changes

2022-09-19 19:05 UTC, serhii-temchenko commented on pallets/ocex/src/tests.rs
> +				snapshot_hash: H256::random(),
Please remove `hash` var as well.

2022-09-20 06:37 UTC, serhii-temchenko approved these changes

2022-09-20 07:55 UTC, Gauthamastro approved these changes

2022-09-20 07:55 UTC, merged