Impl token whitelisting for OCEX Pallet
Polkadex-Substrate/Polkadex pull request #527
Opened 2022-09-21 04:46 UTC by zktony

Impl token whitelisting for OCEX Pallet. Will close #464.

2022-09-26 08:13 UTC, serhii-temchenko submitted a review, later dismissed

2022-09-27 12:30 UTC, Gauthamastro commented
The claim_withdrawal should also check for allow-listing configs. Please change all terminology to allow-listing and block-listing.

2022-09-27 12:30 UTC, Gauthamastro requested changes
As given above

2022-09-29 09:48 UTC, Gauthamastro approved these changes, later dismissed

2022-09-29 20:52 UTC, serhii-temchenko approved these changes, later dismissed

2022-10-04 09:22 UTC, merged