Made certificate validity timestamp a variable for flexible external calls and governance update
Polkadex-Substrate/Polkadex pull request #572
Opened 2022-10-07 12:28 UTC by zktony

Made certificate validity timestamp a variable for flexible external calls and governance update. Will close #

2022-10-10 09:06 UTC, serhii-temchenko requested changes

2022-10-10 09:06 UTC, serhii-temchenko commented on pallets/ocex/Cargo.toml
> +ias-verify = { default-features = false, version = "0.1.5", branch = "532", git = "https://github.com/Polkadex-Substrate/pallets" }
Please merge related branch with PR it's approved (I don't have rights to do that in that repo) and change it back to `polkadot-v0.9.28`.

2022-10-10 13:26 UTC, zktony commented on pallets/ocex/Cargo.toml
> +ias-verify = { default-features = false, version = "0.1.5", branch = "532", git = "https://github.com/Polkadex-Substrate/pallets" }
done

2022-10-10 17:18 UTC, serhii-temchenko approved these changes, later dismissed

2022-10-10 17:19 UTC, serhii-temchenko commented
Also not really sure how this PR decreases code coverage for 25.87%....

2022-10-11 08:41 UTC, serhii-temchenko approved these changes

2022-10-11 09:19 UTC, Gauthamastro approved these changes

2022-10-11 09:20 UTC, merged