Thea Staking Pallet
Polkadex-Substrate/Polkadex pull request #599
Opened 2023-01-09 04:25 UTC by Gauthamastro

It provides a way to manage thea relayers for multiple networks, it's roughly inspired by Parity's staking pallet. 

Rewards and Misbehaviour management will not be included in this PR. It will be implemented in another PR when rewards and misbehaviours are enums are defined.

Test cases are not implemented yet.

Don't review yet.

2023-01-12 11:04 UTC, felixfaisal commented
This PR is ready for review @serhii-temchenko

2023-01-13 00:18 UTC, serhii-temchenko requested changes

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/README.md
> +License: Unlicense
Please remove this default readme

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +	//pub type StakingInfo = (Config::AccountId, Exposure<Config, <dyn Config>::AccountId>);
Please remove

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		// TODO: @Faizal uncomment the code below for session change hook
@felixfaisal FYI

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +
Please remove if no logic here

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		#[pallet::weight(10000)]
Please add todo with issue reference about benchmarking to control this question.

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		}
Please add documentation

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +			bls_key: BLSPublicKey,
Please add documentation

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		pub fn nominate(origin: OriginFor<T>, candidate: T::AccountId) -> DispatchResult {
Please add documentation

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		pub fn bond(origin: OriginFor<T>, amount: BalanceOf<T>) -> DispatchResult {
Please add documentation

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +				//FIXME: Handle this case
Please fix

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		pub fn unbond(origin: OriginFor<T>, amount: BalanceOf<T>) -> DispatchResult {
Please add documentation

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		pub fn withdraw_unbonded(origin: OriginFor<T>) -> DispatchResult {
Please add documentation

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		pub fn remove_candidate(origin: OriginFor<T>, network: Network) -> DispatchResult {
Please add documentation

2023-01-13 00:18 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		// TODO: @Faizal uncomment this when session change trait is ready.
@felixfaisal FYI

2023-01-13 05:39 UTC, zktony commented on pallets/thea-staking/README.md
> +License: Unlicense
done

2023-01-13 05:40 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +	//pub type StakingInfo = (Config::AccountId, Exposure<Config, <dyn Config>::AccountId>);
done

2023-01-13 05:56 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +
done

2023-01-13 05:56 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +		#[pallet::weight(10000)]
done

2023-01-13 07:31 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +		}
done

2023-01-13 07:31 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +		pub fn nominate(origin: OriginFor<T>, candidate: T::AccountId) -> DispatchResult {
done

2023-01-13 07:31 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +		pub fn unbond(origin: OriginFor<T>, amount: BalanceOf<T>) -> DispatchResult {
done

2023-01-13 07:32 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +		pub fn remove_candidate(origin: OriginFor<T>, network: Network) -> DispatchResult {
done

2023-01-13 07:32 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +		pub fn withdraw_unbonded(origin: OriginFor<T>) -> DispatchResult {
done

2023-01-13 07:42 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +		pub fn bond(origin: OriginFor<T>, amount: BalanceOf<T>) -> DispatchResult {
done

2023-01-13 07:42 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +			bls_key: BLSPublicKey,
done

2023-01-13 07:43 UTC, zktony commented on pallets/thea-staking/src/lib.rs
> +				//FIXME: Handle this case
done

2023-01-14 11:14 UTC, serhii-temchenko approved these changes

2023-01-17 06:47 UTC, nakul1010 commented on pallets/thea-staking/src/lib.rs
> +		// TODO: @Faizal uncomment the code below for session change hook
Issue created: https://github.com/Polkadex-Substrate/Polkadex/issues/610

2023-01-17 06:48 UTC, nakul1010 commented on pallets/thea-staking/src/lib.rs
> +		// TODO: @Faizal uncomment this when session change trait is ready.
issue created: https://github.com/Polkadex-Substrate/Polkadex/issues/610

2023-01-17 06:48 UTC, nakul1010 approved these changes
LGTM

2023-01-17 06:48 UTC, merged