Integration between thea & staking pallet
Polkadex-Substrate/Polkadex pull request #615
Opened 2023-01-18 06:56 UTC by nakul1010

Closes issue #610.

2023-01-19 08:49 UTC, serhii-temchenko requested changes

2023-01-19 08:49 UTC, serhii-temchenko commented on pallets/thea-staking/Cargo.toml
> +chainbridge = {path = "../chainbridge", default-features = false}
Please use common formatting with spaces between parenthesis.

2023-01-19 08:49 UTC, serhii-temchenko commented on pallets/thea-staking/Cargo.toml
> +thea = { path = "../thea", default-features = false}
Same

2023-01-19 08:49 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		>;
I assume todo could be removed?

2023-01-19 08:49 UTC, serhii-temchenko commented on pallets/thea/Cargo.toml
> +thea-staking = {path = "../thea-staking", default-features = false}
Please fix it here as well

2023-01-19 08:49 UTC, serhii-temchenko commented on thea-primitives/Cargo.toml
> +]
Please add empty line at the end

2023-01-19 21:27 UTC, serhii-temchenko approved these changes

2023-01-20 06:09 UTC, Gauthamastro approved these changes

2023-01-20 06:09 UTC, merged