Reimplemented Deposit and Withdrawal Extrinsics
Polkadex-Substrate/Polkadex pull request #625
Opened 2023-01-24 16:11 UTC by zktony

## Describe your changes
* Reimplemented Deposit and Withdrawal Extrinsics.
* Added XCM Support.
* Added test cases.
 
## Issue ticket number and link
[#4](https://github.com/Polkadex-Substrate/thea/issues/4)

2023-01-25 05:28 UTC, zktony commented
@nakul1010, please review this PR. While resolving merge conflicts, I may have removed your code. 
|This PR requires @nakul1010 approval|

2023-01-25 05:35 UTC, nakul1010 approved these changes, later dismissed
Didn't affect any of my prev code written. LGTM

2023-01-25 23:30 UTC, serhii-temchenko commented
@zktony is it ready to be reviewed? If so - please add a label so I could see that it is ready.

2023-01-27 00:15 UTC, serhii-temchenko requested changes

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/asset-handler/Cargo.toml
> +thea-primitives = {path = "../../thea-primitives", default-features = false}
Please add places before and after `{}`

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/asset-handler/src/lib.rs
> +			let asset_id = Self::get_asset_id(derived_asset_id);
I'd moved this comment on the `get_asset_id` function directly.

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/asset-handler/src/lib.rs
> +		) -> DispatchResult {
Please add params into the dockblock.

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/thea-staking/Cargo.toml
> +try-runtime = ["frame-support/try-runtime"]
Please add empty line at the end of file

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/thea/Cargo.toml
> +thea-primitives = {path = "../../thea-primitives", default-features = false}
Please add spaces before and after `{}`

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +		) -> DispatchResult {
Please move back parameters definition within the dockblock which removed in this PR for this method.

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
>  		) -> DispatchResult {
Please add parameters into the dockblock

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +			current_ecdsa.try_push(who.clone()).unwrap();
Please handle properly results without `unprap`s

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
>  		pub fn withdraw(
Please move back parameters into the dockblock.

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +		) -> DispatchResult {
Please extend the dockblock with parameters description

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +			//#[allow(clippy::unnecessary_lazy_evaluations)]
Please remove

2023-01-27 00:15 UTC, serhii-temchenko commented on pallets/thea/src/tests.rs
> +// use frame_support::metadata::StorageEntryModifier::Default as ;
Please remove

2023-02-02 22:39 UTC, serhii-temchenko approved these changes

2023-02-06 12:45 UTC, Gauthamastro approved these changes

2023-02-06 12:46 UTC, merged