Implemented pallet for cross-chain governance on Solo-chain
Polkadex-Substrate/Polkadex pull request #628
Opened 2023-01-25 13:02 UTC by zktony

## Describe your changes
Thea Governance Pallet on Solo-chain.
The following things are implemented:-
* Apply for Candidature for Thea Council. (Provide keys for current network)
* Approve candidature. (Need majority of General Council or Root)
* Remove existing members. (Need majority of General Council or Root)

## Issue ticket number and link
Partially closes https://github.com/Polkadex-Substrate/thea/issues/78

2023-01-25 23:29 UTC, serhii-temchenko commented
@zktony is it ready to be reviewed? If so - please add a label so I could see that it is ready.

2023-01-26 05:24 UTC, zktony commented
> @zktony is it ready to be reviewed? If so - please add a label so I could see that it is ready.

Sorry, I was waiting for checks to pass.

2023-01-26 07:21 UTC, Gauthamastro requested changes

2023-01-26 07:21 UTC, Gauthamastro commented on pallets/thea-cross-chain-governance/src/lib.rs
> +		type StakingAmount: Get<u128>;
Use the balance type from primitives

2023-01-26 07:21 UTC, Gauthamastro commented on pallets/thea-cross-chain-governance/src/lib.rs
> +		pub fn apply_for_candidature(origin: OriginFor<T>, keys_list: KeysMap) -> DispatchResult {
Also, add the check if an identity is attached to this account, if not reject

2023-01-26 07:21 UTC, Gauthamastro commented on pallets/thea-cross-chain-governance/src/lib.rs
> +		StorageMap<_, Blake2_128Concat, T::AccountId, KeysMap, OptionQuery>;
I prefer it to be a boundedVec than storagemap

2023-01-26 07:21 UTC, Gauthamastro commented on pallets/thea-cross-chain-governance/src/lib.rs
> +		StorageMap<_, Blake2_128Concat, T::AccountId, KeysMap, OptionQuery>;
Same here.

2023-01-26 07:21 UTC, Gauthamastro commented on pallets/thea-cross-chain-governance/src/lib.rs
> +			candidate: T::AccountId,
A bounded vector of accounts should be provided.

2023-01-26 23:42 UTC, serhii-temchenko requested changes
Minor improvements required.
Thanks for nice written tests!

2023-01-26 23:42 UTC, serhii-temchenko commented on pallets/thea-cross-chain-governance/Cargo.toml
> +parity-scale-codec = {workspace = true, default-features = false }
Please add space after `{`

2023-01-26 23:42 UTC, serhii-temchenko commented on pallets/thea-cross-chain-governance/Cargo.toml
> +frame-benchmarking = { default-features = false, workspace = true , optional = true}
Please add space before `}`

2023-01-26 23:42 UTC, serhii-temchenko commented on pallets/thea-cross-chain-governance/src/lib.rs
> +		pub fn apply_for_candidature(origin: OriginFor<T>, keys_list: KeysMap) -> DispatchResult {
Please add parameters in to the dockblock with proper description.

2023-01-26 23:42 UTC, serhii-temchenko commented on pallets/thea-cross-chain-governance/src/lib.rs
> +		) -> DispatchResult {
Please add parameters in to the dockblock with proper description.

2023-01-26 23:42 UTC, serhii-temchenko commented on pallets/thea-cross-chain-governance/src/lib.rs
> +		pub fn add_new_keys(origin: OriginFor<T>, new_keys: KeysMap) -> DispatchResult {
Please add parameters in to the dockblock with proper description.

2023-01-26 23:42 UTC, serhii-temchenko commented on pallets/thea-cross-chain-governance/src/lib.rs
> +		pub fn remove_candidate(origin: OriginFor<T>, candidate: T::AccountId) -> DispatchResult {
Please add parameters in to the dockblock with proper description.

2023-01-26 23:42 UTC, serhii-temchenko commented on runtime/Cargo.toml
> +thea-cross-chain-governance = {path = "../pallets/thea-cross-chain-governance", default-features = false}
Same with spaces before and after `{}`

2023-02-01 12:48 UTC, zktony commented on pallets/thea-cross-chain-governance/src/lib.rs
> +		type StakingAmount: Get<u128>;
done

2023-02-01 13:51 UTC, zktony commented on runtime/Cargo.toml
> +thea-cross-chain-governance = {path = "../pallets/thea-cross-chain-governance", default-features = false}
done

2023-02-01 22:45 UTC, serhii-temchenko commented
@zktony I'll move this PR to `InProgress` label since it looks like work on comments still ongoing. Please move it back to `PleaseReview` when it will be ready so I could understand that it could be re-reviewed.

2023-02-03 00:00 UTC, serhii-temchenko approved these changes

2023-02-07 05:16 UTC, Gauthamastro approved these changes

2023-02-07 05:16 UTC, merged