Thea Pallet: Key Rotation
Polkadex-Substrate/Polkadex pull request #636
Opened 2023-02-02 09:20 UTC by Gauthamastro

Relayers should use Queued Relayers of Thea Staking Pallet and Active Relayers of Thea pallet for operations. Thea pallet will generate an ingress message when the key updation is complete on foreign chain after which new relayers can start processing withdrawals.  Queued Relayers of Thea Staking Pallet is used to pre-generate Thea Public key and Offline Stages  for next set and update the on-chain state about it.

2023-02-02 09:21 UTC, Gauthamastro commented
Sending new public key back to on-chain state

2023-02-03 08:49 UTC, felixfaisal requested changes

2023-02-03 08:49 UTC, felixfaisal commented on pallets/thea/src/lib.rs
> +			);
We should track this hash, as there exist a scenario that can lead to replay attack if relayers remain unchanged over different sets .

2023-02-17 05:59 UTC, felixfaisal commented
Resolves #647 
Resolves #645 (In events rather than in `struct` as mentioned in the issue)

2023-02-17 11:24 UTC, serhii-temchenko requested changes

2023-02-17 11:24 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +		pub fn thea_relayers_reset_rotation(
Please add docblock as on other extrinsics

2023-02-20 10:32 UTC, felixfaisal commented on pallets/thea/src/lib.rs
> +		pub fn thea_relayers_reset_rotation(
Done ✅

2023-02-20 18:51 UTC, serhii-temchenko approved these changes

2023-02-21 05:29 UTC, felixfaisal approved these changes

2023-02-21 06:19 UTC, merged