Testcases for 616
Polkadex-Substrate/Polkadex pull request #638
Opened 2023-02-07 15:22 UTC by nakul1010

2023-03-10 08:33 UTC, serhii-temchenko requested changes

2023-03-10 08:33 UTC, serhii-temchenko commented on client/Cargo.toml
> +polkadex-extrinsic = {path = "../polkadex-extrinsic"}
Please add spaces before `}` and after `{`.

2023-03-10 08:33 UTC, serhii-temchenko commented on client/Cargo.toml
> +polkadex-extrinsic = {path = "../polkadex-extrinsic"}
Please add an empty line at the end of file

2023-03-10 08:33 UTC, serhii-temchenko commented on pallets/assets-transaction-payment/src/lib.rs
> +			//If the asset id is zero, then we treat that case as payment in PDEX,
I assume this comment moved into the `else` case. Please remove it from here.

2023-03-10 08:33 UTC, serhii-temchenko commented on polkadex-extrinsic/Cargo.toml
> +]
Please add an empty line at the end of file

2023-03-10 08:33 UTC, serhii-temchenko commented on pallets/assets-transaction-payment/Cargo.toml
> +]
Please add empty line at the end of file

2023-03-10 08:33 UTC, serhii-temchenko commented on pallets/assets-transaction-payment/src/test.rs
> +		// Error::<Test>::TokenNotAllowlisted));
Is it valid logic to do? I mean - isn't remove operations supposed to be idempotent? it's means - result should not throw error even if it's not found or not "allowlisted", I think logic in this extrinsic implemented in this way no?   So to test this extrinsic - there should be asserted that remove of not "allowlisted" asset will return ok result, remove of "allowlisted" asset will remove it from the collection and of course that  called by the root.

2023-03-10 08:33 UTC, serhii-temchenko commented on pallets/assets-transaction-payment/src/test.rs
> +		assert_ok!(AssetsTransactionPayment::allow_list_token_for_fees(Origin::root(), asset));
After this assertion still should be asserted that it was added into the collection e.g.:
```rust
assert_eq!(<AllowedAssets<Test>>::get(), vec![asset]);
```

2023-03-10 08:33 UTC, serhii-temchenko commented on pallets/assets-transaction-payment/src/test.rs
> +pub fn info_from_weight(w: Weight) -> DispatchInfo {
Empty string before this line

2023-03-10 08:57 UTC, 35359595 commented
can we have more specific name for this crate? extrinsic should preserve one meaning from substrate to avoid any confusion.

2023-03-17 06:51 UTC, nakul1010 commented on pallets/assets-transaction-payment/src/test.rs
> +		// Error::<Test>::TokenNotAllowlisted));
yes added both the test cases

2023-03-17 06:52 UTC, nakul1010 commented on pallets/assets-transaction-payment/src/test.rs
> +		assert_ok!(AssetsTransactionPayment::allow_list_token_for_fees(Origin::root(), asset));
added in latest test case `block_token_for_fees_when_token_allowlisted`

2023-03-17 06:53 UTC, nakul1010 commented on pallets/assets-transaction-payment/src/test.rs
> +pub fn info_from_weight(w: Weight) -> DispatchInfo {
Done

2023-03-17 06:57 UTC, nakul1010 commented
@serhii-temchenko! Thank you for including the CI commit code from the develop branch into this branch.

2023-03-17 07:03 UTC, nakul1010 commented
> can we have more specific name for this crate? extrinsic should preserve one meaning from substrate to avoid any confusion.

I assume u are mentioning the `polkadex-extrinsic` crate, does `wallet-connect` work ?

2023-03-17 07:45 UTC, 35359595 commented
> > can we have more specific name for this crate? extrinsic should preserve one meaning from substrate to avoid any confusion.
> 
> I assume u are mentioning the `polkadex-extrinsic` crate, can I change the name to `wallet-connect`? 

it also sounds like action. is wallet-connector describing purpose of this crate?

2023-03-17 09:31 UTC, nakul1010 commented
> > > can we have more specific name for this crate? extrinsic should preserve one meaning from substrate to avoid any confusion.
> > 
> > 
> > I assume u are mentioning the `polkadex-extrinsic` crate, can I change the name to `wallet-connect`?
> 
> it also sounds like action. is wallet-connector describing purpose of this crate?

yes, the crate basically has the ability to send transactions using any generic wallet that is not supported by substrate.

2023-03-17 11:03 UTC, serhii-temchenko approved these changes

2023-03-17 11:26 UTC, merged