Added PDEX Token Handler
Polkadex-Substrate/Polkadex pull request #642
Opened 2023-02-09 14:54 UTC by zktony

Added PDEX Token Handler. 

_Testcases to be added._

2023-02-12 20:17 UTC, serhii-temchenko requested changes

2023-02-12 20:17 UTC, serhii-temchenko commented on pallets/asset-handler/src/lib.rs
> +		) -> Result<(), DispatchError> {
Please add documentation

2023-02-12 20:17 UTC, serhii-temchenko commented on pallets/asset-handler/src/lib.rs
> +		pub fn lock_pdex_asset(amount: u128, who: T::AccountId) -> DispatchResult {
Same

2023-02-12 20:17 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +			};
Please remove todo, looks like it's outdated and fixed already

2023-02-12 20:17 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +			};
With this approach extra query to the storage will be executed always, but it's can be optional and executed only if `asset_id != T::PolkadexAssetId::get()`. So I think it's could be changed to something like this:

```rust
			let network = if asset_id == T::PolkadexAssetId::get() {
				1
			} else {
				let (network, ..) = asset_handler::pallet::Pallet::<T>::get_thea_assets(asset_id);
				network
			};

```

2023-02-15 18:45 UTC, serhii-temchenko approved these changes

2023-02-20 05:46 UTC, Gauthamastro approved these changes

2023-02-20 05:46 UTC, merged