feat: Rewards Payout for Relayers
Polkadex-Substrate/Polkadex pull request #651
Opened 2023-02-27 09:13 UTC by felixfaisal

This PR implements rewards for Relayers, based on `Piece wise linear curve` , Things yet to do 
- [ ] Multiple unit tests 
- [ ] End to End Tests with Thea Bridge 
- [ ] Multiple Network Relayers and Nominators 
- [ ] Test Calculations 
- [ ] Cleanup code ( Remove unwraps and clippy fixes ) 

The core functions responsible for calculating rewards and distributing are implemented, It will be ready for review once the above is completed.

2023-03-02 00:08 UTC, serhii-temchenko commented
@felixfaisal please merge dev into this branch. It will fix current errors from clippy.

2023-03-02 07:08 UTC, felixfaisal commented
Thanks @serhii-temchenko , I've pulled changes from `Develop`

2023-03-02 22:03 UTC, serhii-temchenko requested changes

2023-03-02 22:03 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +			Ok(())
Please add proper dockblock

2023-03-02 22:03 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		StorageMap<_, Blake2_128Concat, u32, BalanceOf<T>, ValueQuery>;
Please add comment as well, as on other members

2023-03-02 22:03 UTC, serhii-temchenko commented on pallets/thea-staking/src/tests.rs
> +//
Please remove

2023-03-02 22:03 UTC, serhii-temchenko commented on runtime/src/lib.rs
> +
Please remove if not needed

2023-03-06 05:05 UTC, felixfaisal commented on pallets/thea-staking/src/lib.rs
> +			Ok(())
Done ✅

2023-03-06 05:08 UTC, felixfaisal commented on pallets/thea-staking/src/lib.rs
> +		StorageMap<_, Blake2_128Concat, u32, BalanceOf<T>, ValueQuery>;
Done ✅

2023-03-06 05:08 UTC, felixfaisal commented on pallets/thea-staking/src/tests.rs
> +//
Removed ✅

2023-03-06 05:09 UTC, felixfaisal commented on runtime/src/lib.rs
> +
Removed ✅

2023-03-06 08:36 UTC, serhii-temchenko approved these changes

2023-03-06 09:52 UTC, Gauthamastro approved these changes

2023-03-06 10:01 UTC, merged