Iv 142
Polkadex-Substrate/Polkadex pull request #662
Opened 2023-03-15 10:52 UTC by 35359595

## Describe your changes
Testing and benchmarks for thea slashing

## Issue ticket number and link
#142 from Thea

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] I removed all Clippy and Formatting Warnings. 
- [ ] I added required Copyrights.

2023-03-23 22:27 UTC, serhii-temchenko requested changes

2023-03-23 22:27 UTC, serhii-temchenko commented on pallets/thea-staking/src/benchmarking.rs
> +// Copyright (C) 2020-2022 Polkadex oü.
Please update to 2023

2023-03-23 22:27 UTC, serhii-temchenko commented on pallets/thea-staking/src/tests.rs
> +		// assert_ok!(TheaStaking::nominate(Origin::signed(nominator), candidate));
Please remove

2023-03-23 22:27 UTC, serhii-temchenko commented on pallets/thea-staking/src/tests.rs
> +fn test_nominate_with_wrong_candidate_returns_candidate_alread_nominated() {
Typo in `alread`

2023-03-23 22:27 UTC, serhii-temchenko commented on pallets/thea-staking/src/tests.rs
> +		// assert_ok!(TheaStaking::nominate(Origin::signed(nominator), candidate));
Same

2023-03-23 22:27 UTC, serhii-temchenko commented on pallets/thea-staking/src/tests.rs
> +
Same

2023-03-23 22:27 UTC, serhii-temchenko commented on pallets/thea-staking/src/tests.rs
> +		// panic!("here");
Same

2023-03-23 22:27 UTC, serhii-temchenko commented on pallets/thea-staking/src/tests.rs
> +		// assert_ok!(TheaStaking::nominate(Origin::signed(nominator), candidate));
Same

2023-03-24 08:14 UTC, 35359595 commented on pallets/thea-staking/src/benchmarking.rs
> +// Copyright (C) 2020-2022 Polkadex oü.
done

2023-03-24 08:14 UTC, 35359595 commented on pallets/thea-staking/src/tests.rs
> +		// assert_ok!(TheaStaking::nominate(Origin::signed(nominator), candidate));
done

2023-03-24 08:14 UTC, 35359595 commented on pallets/thea-staking/src/tests.rs
> +fn test_nominate_with_wrong_candidate_returns_candidate_alread_nominated() {
done

2023-03-24 08:14 UTC, 35359595 commented on pallets/thea-staking/src/tests.rs
> +
done

2023-03-24 08:15 UTC, 35359595 commented on pallets/thea-staking/src/tests.rs
> +		// assert_ok!(TheaStaking::nominate(Origin::signed(nominator), candidate));
done

2023-03-24 08:15 UTC, 35359595 commented on pallets/thea-staking/src/tests.rs
> +		// panic!("here");
done

2023-03-24 08:16 UTC, 35359595 commented on pallets/thea-staking/src/tests.rs
> +		// assert_ok!(TheaStaking::nominate(Origin::signed(nominator), candidate));
done

2023-03-24 09:59 UTC, serhii-temchenko approved these changes

2023-03-24 12:29 UTC, felixfaisal approved these changes
LGTM

2023-03-24 14:06 UTC, merged