fixed slashing
Polkadex-Substrate/Polkadex pull request #664
Opened 2023-03-16 09:17 UTC by nakul1010

Pr Fixes #663.

2023-03-16 22:00 UTC, serhii-temchenko requested changes

2023-03-16 22:00 UTC, serhii-temchenko commented on pallets/thea-staking/src/lib.rs
> +		AmountToStashGreaterThanBondedAmount,
I assume typo in `Stash` in comment and in enum variant

2023-03-17 05:02 UTC, nakul1010 commented on pallets/thea-staking/src/lib.rs
> +		AmountToStashGreaterThanBondedAmount,
Done

2023-03-17 07:23 UTC, serhii-temchenko approved these changes

2023-03-17 08:18 UTC, 35359595 approved these changes
LGTM

2023-03-17 09:23 UTC, merged