Test ceses for V2
Polkadex-Substrate/Polkadex pull request #675
Opened 2023-03-23 13:52 UTC by nakul1010

Fixes [703](https://github.com/Polkadex-Substrate/orderbook/issues/704)

2023-03-27 09:36 UTC, nakul1010 commented
@Gauthamastro CI is failing for base branch(`gj-ob`) hence  will fail for the current branch as well.

2023-03-27 10:14 UTC, Gauthamastro commented on clients/orderbook/polkadex/.keystore/89f6bf5ba250773f90be3336ab2418ffa35d5b1770ea84e43c1d3a711d61c1bb4223653550c93e604899524d1a2ed45c177a8172d10d42042f4ba8244cb9cc49d1e10206160d11196005c69c7cc3a79625e05b7683cea3c6d07094dbac29c82f
Don't save these

2023-03-29 21:43 UTC, serhii-temchenko requested changes
> @Gauthamastro CI is failing for the base branch(gj-ob) hence will fail for the current branch as well. OCEX pallet needs to be fixed.

Could base branch be fixed before merging something else to not multiply potential problems in one branch?

2023-03-30 17:35 UTC, serhii-temchenko approved these changes

2023-03-31 02:51 UTC, merged