Iv 614
Polkadex-Substrate/Polkadex pull request #676
Opened 2023-03-24 14:18 UTC by 35359595

## Describe your changes
Tests for thea pallet including one for on_initialize and un-ignored one for BLS signature validation

## Issue ticket number and link
Closes #614 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] I removed all Clippy and Formatting Warnings. 
- [ ] I added required Copyrights.

2023-03-25 07:50 UTC, serhii-temchenko requested changes
Not tested next cases:
1) - [x] `approve_deposit` with invalid origin
2) - [x]  Throw of `TokenTypeNotHandled` in `approve_deposit` extrinsic e.g.  by providing `TokenType` arg with `NonFungible`, `Generic` or `Fungible` witch value other than 1 or 2 - should return this error ([here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L979-L990)).
3) - [x] `BoundedVectorOverflow` [here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L907) is not tested.
4) - [ ] [claim_deposit](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L404-L449) extrinsic is not tested at all. (in the list of related issue).
5) - [x] [batch_withdrawal_complete](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L451-L477) extrinsic is not tested at all. (in the list of related issue).
6) - [x] [withdraw](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L479-L503) extrinsic failing cases not tested like: 
- - [x] `BadOrigin` error [here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L498). 
- - [x] `TheaKeyRotationInPlace` [here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L740).
- - [x] WithdrawalNotAllowed [here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L745).
7) - [x] `set_withdrawal_fee` BadOrigin error not tested [here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L517).
8) - [ ] [thea_key_rotation_complete](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L523-L580) is not tested at all.
9) - [ ] [set_thea_key_complete](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L582-L630) is not tested at all.
10) - [ ] [thea_queued_queued_public_key](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L632-L687) is not tested at all.
11) - [x] [thea_relayers_reset_rotation](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L689-L717) is not tested at  all.

2023-03-29 10:53 UTC, 35359595 commented
> Not tested next cases:
> 
>     1. * [x]  `approve_deposit` with invalid origin
> 
>     2. * [x]   Throw of `TokenTypeNotHandled` in `approve_deposit` extrinsic e.g.  by providing `TokenType` arg with `NonFungible`, `Generic` or `Fungible` witch value other than 1 or 2 - should return this error ([here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L979-L990)).
> 
>     3. * [x]  `BoundedVectorOverflow` [here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L907) is not tested.
> 
>     4. * [x]  [claim_deposit](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L404-L449) extrinsic is not tested at all. (in the list of related issue).
> 
>     5. * [x]  [batch_withdrawal_complete](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L451-L477) extrinsic is not tested at all. (in the list of related issue).
> 
>     6. * [x]  [withdraw](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L479-L503) extrinsic failing cases not tested like:
> 
> 
>     * * [x]  `BadOrigin` error [here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L498).
> 
>     * * [x]  `TheaKeyRotationInPlace` [here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L740).
> 
>     * * [x]  WithdrawalNotAllowed [here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L745).
> 
> 
>     7. * [x]  `set_withdrawal_fee` BadOrigin error not tested [here](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L517).
> 
>     8. * [x]  [thea_key_rotation_complete](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L523-L580) is not tested at all.
> 
>     9. * [x]  [set_thea_key_complete](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L582-L630) is not tested at all.
> 
>     10. * [x]  [thea_queued_queued_public_key](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L632-L687) is not tested at all.
> 
>     11. * [x]  [thea_relayers_reset_rotation](https://github.com/Polkadex-Substrate/Polkadex/blob/9d2add957b3195b1c259f66046ae99d426341da7/pallets/thea/src/lib.rs#L689-L717) is not tested at  all.

done

2023-03-29 18:48 UTC, serhii-temchenko approved these changes, later dismissed
Nice result! Tests coverage increased on +12.30%!

2023-03-30 08:38 UTC, felixfaisal requested changes, later dismissed

2023-03-30 08:38 UTC, felixfaisal commented on thea-primitives/src/lib.rs
> +			if x as usize >= bls_public_keys.len() {
Let's say bls_public_key is empty, therefore it's length is `0` 
We get a map, whose 0th bit is set, Therefore it will be something like `for x in [0]` 

Then we have the if condition which will still work since `0` == `0` and will try to access the `0 index` element resulting in a panic.

2023-03-30 13:03 UTC, 35359595 commented on thea-primitives/src/lib.rs
> +			if x as usize >= bls_public_keys.len() {
good catch, I'm adding check for keys not been empty as start check in the method.

2023-03-30 13:20 UTC, serhii-temchenko approved these changes, later dismissed

2023-03-30 17:56 UTC, serhii-temchenko approved these changes, later dismissed

2023-04-05 12:38 UTC, Gauthamastro approved these changes, later dismissed

2023-04-05 13:02 UTC, Gauthamastro commented
@35359595 test's are failing

2023-04-07 11:24 UTC, serhii-temchenko approved these changes

2023-04-07 11:31 UTC, serhii-temchenko commented
> @35359595 test's are failing

Fixed. @Gauthamastro please review.

2023-04-07 13:33 UTC, Gauthamastro approved these changes

2023-04-07 13:36 UTC, merged