V2 recovery
Polkadex-Substrate/Polkadex pull request #688
Opened 2023-03-31 08:36 UTC by nakul1010

Fixes Part 1 of [#733](https://github.com/Polkadex-Substrate/orderbook/issues/733)

2023-03-31 11:09 UTC, serhii-temchenko requested changes
I did some minor changes in a latest commits. But please take a look into error handling comments.

2023-03-31 11:09 UTC, serhii-temchenko commented on clients/orderbook/rpc/src/lib.rs
> +				match trie.get(&account_asset.encode()).unwrap() {
Should be properly handled.

2023-03-31 11:09 UTC, serhii-temchenko commented on clients/orderbook/rpc/src/lib.rs
> +						let account_balance = Decimal::decode(&mut &data[..]).unwrap();
Should be properly handled.

2023-03-31 11:09 UTC, serhii-temchenko commented on clients/orderbook/rpc/src/lib.rs
> +					None => {},
Some log should be here?

2023-03-31 11:09 UTC, serhii-temchenko commented on primitives/orderbook/Cargo.toml
> +futures = "0.3"
I assume this was added by mistake since not used. Removing it.

2023-03-31 14:39 UTC, serhii-temchenko approved these changes

2023-04-01 04:24 UTC, Gauthamastro approved these changes
General logic looks good, but the code quality needs to be improved, especially inside service.rs and serializing the data in RPC calls.

@nakul1010

2023-04-01 04:25 UTC, merged