Added inline docs for Orderbook Client
Polkadex-Substrate/Polkadex pull request #704
Opened 2023-04-10 04:43 UTC by zktony

## Describe your changes
Added inline docs for Orderbook Client.

2023-04-12 13:24 UTC, Gauthamastro submitted a review, later dismissed

2023-04-13 12:31 UTC, serhii-temchenko requested changes
About which level of the documentation we are speaking about here in the scope of this task? If about proper documentation for `orderbook` crate under `Polkadex/clients/orderbook` folder - than a lot of public api documentation is still missing and should be added (like [here](https://github.com/Polkadex-Substrate/Polkadex/blob/8857f7d5404c9a6284f89b28d79119a051e1ff36/clients/orderbook/src/utils.rs#L27) or [here](https://github.com/Polkadex-Substrate/Polkadex/blob/8857f7d5404c9a6284f89b28d79119a051e1ff36/clients/orderbook/src/worker.rs#L1107), or [here](https://github.com/Polkadex-Substrate/Polkadex/blob/8857f7d5404c9a6284f89b28d79119a051e1ff36/clients/orderbook/src/worker.rs#L58-L64)). As well as module-level or crate-level documentation. Please check all modules (besides tests and mocks etc.) and make sure everything is properly covered.

Please refer rust [documentation](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html) "how to" to write proper documentation and please make it consistent with other project parts.

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/rpc/src/lib.rs
> +	 */
From the rust point of view - this doc comments syntax is generates the same output as `///` syntax, but in the scope of the project - this is different syntax and makes documentation inconsistent. Consistency should be chaised even in docs so if we are using in all places `///` syntax - please stick to it.

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/rpc/src/lib.rs
> +	 */
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/rpc/src/lib.rs
> +	message - The ObMessage to be sent.
Don't forget to add `*` before arg name and \` around  it (e.g. * \`message\` like [here](https://github.com/Polkadex-Substrate/Polkadex/blob/mainnet-release/pallets/asset-handler/src/lib.rs#L306-L309)).

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// stid - The unique identifier for the snapshot.
When this docblock will be compiled to the html by the cargo doc - it will not have proper styling so please use common documentation style

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// num - The block number to import.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// active_set - The list of active validators.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// stid - The identifier for the snapshot to be generated.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// action - The message to be processed.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// summary - The snapshot summary containing the state change ID and other information.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// action - a reference to the ObMessage received.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// snapshot_id - the ID of the snapshot.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// summary - a reference to the SnapshotSummary to load.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// self - mutable reference to the current object.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// peer - an optional PeerId to send the messages to.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// messages - a reference to a vector of ObMessage to process.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// remote - an optional PeerId to respond to.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// remote - an optional PeerId to respond to.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// data - a reference to the chunk of data to process.
Same

2023-04-13 12:31 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	/// remote - an optional PeerId to respond to.
Same

2023-04-14 07:39 UTC, zktony commented
Got it

2023-04-18 06:39 UTC, serhii-temchenko commented
> About which level of the documentation we are speaking about here in the scope of this task? If about proper documentation for `orderbook` crate under `Polkadex/clients/orderbook` folder - than a lot of public api documentation is still missing and should be added (like [here](https://github.com/Polkadex-Substrate/Polkadex/blob/8857f7d5404c9a6284f89b28d79119a051e1ff36/clients/orderbook/src/utils.rs#L27) or [here](https://github.com/Polkadex-Substrate/Polkadex/blob/8857f7d5404c9a6284f89b28d79119a051e1ff36/clients/orderbook/src/worker.rs#L1107), or [here](https://github.com/Polkadex-Substrate/Polkadex/blob/8857f7d5404c9a6284f89b28d79119a051e1ff36/clients/orderbook/src/worker.rs#L58-L64)). As well as module-level or crate-level documentation. Please check all modules (besides tests and mocks etc.) and make sure everything is properly covered.
> 
> Please refer rust [documentation](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html) "how to" to write proper documentation and please make it consistent with other project parts.

Hey @zktony, is it really ready for re-review? if so - did you noted my previous message which I'm quoting here? in the updates after review I can see only update of existed docs but no new one.

2023-04-18 06:43 UTC, serhii-temchenko requested changes
> About which level of the documentation we are speaking about here in the scope of this task? If about proper documentation for `orderbook` crate under `Polkadex/clients/orderbook` folder - than a lot of public api documentation is still missing and should be added (like [here](https://github.com/Polkadex-Substrate/Polkadex/blob/8857f7d5404c9a6284f89b28d79119a051e1ff36/clients/orderbook/src/utils.rs#L27) or [here](https://github.com/Polkadex-Substrate/Polkadex/blob/8857f7d5404c9a6284f89b28d79119a051e1ff36/clients/orderbook/src/worker.rs#L1107), or [here](https://github.com/Polkadex-Substrate/Polkadex/blob/8857f7d5404c9a6284f89b28d79119a051e1ff36/clients/orderbook/src/worker.rs#L58-L64)). As well as module-level or crate-level documentation. Please check all modules (besides tests and mocks etc.) and make sure everything is properly covered.
> 
> Please refer rust [documentation](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html) "how to" to write proper documentation and please make it consistent with other project parts.

Hey @zktony, is it really ready for re-review? if so - did you noted my previous message which I'm quoting here? in the updates after review I can see only update of existed docs but no new one. Please add module and crate-level docs and cover pointed places.

2023-06-05 15:33 UTC, closed without merging