Iv oom
Polkadex-Substrate/Polkadex pull request #793
Opened 2023-06-12 10:18 UTC by 35359595

## Describe your changes

Clients are no longer blocked for message processing before runtime is available.

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] I removed all Clippy and Formatting Warnings. 
- [ ] I added required Copyrights.

2023-06-12 10:34 UTC, Gauthamastro submitted a review, later dismissed

2023-06-12 13:15 UTC, nuel77 commented
orderbook worker is fetching runtime api. it is not waiting for pallet to be available now.
<img width="1150" alt="image" src="https://github.com/Polkadex-Substrate/Polkadex/assets/50878033/7c6fdd92-93e1-41c0-83b8-3a070583ee4b">

2023-06-12 19:51 UTC, 35359595 commented
> orderbook worker is fetching runtime api. it is not waiting for pallet to be available now. <img alt="image" width="1150" src="https://user-images.githubusercontent.com/50878033/245154821-7c6fdd92-93e1-41c0-83b8-3a070583ee4b.png">

this is not a bug, it's intentional to allow client's messaging progress and release cache. we need to re-thing this snapshot loading on empty chain, possibly simply by demoting this error to warning.

2023-06-13 03:28 UTC, serhii-temchenko requested changes

2023-06-13 03:28 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +	// is runtime upgraded and client can process
```suggestion
	/// is runtime upgraded and client can process
```
I'd suggest use doc syntax (e.g. `///`) here on pub scope as on other pub members...

2023-06-13 03:28 UTC, serhii-temchenko commented on clients/orderbook/src/worker.rs
> +					}	else {
```suggestion
					} else {
```

Code style. Extra space should be removed.

2023-06-13 03:33 UTC, Gauthamastro commented
> > orderbook worker is fetching runtime api. it is not waiting for pallet to be available now. <img alt="image" width="1150" src="https://user-images.githubusercontent.com/50878033/245154821-7c6fdd92-93e1-41c0-83b8-3a070583ee4b.png">
> 
> this is not a bug, it's intentional to allow client's messaging progress and release cache. we need to re-thing this snapshot loading on empty chain, possibly simply by demoting this error to warning.

It will result in an inconsistent state and there will be lots of changes in the worker logic, which we need to retest for corner cases. I will raise a PR with minimum changes

2023-06-13 09:01 UTC, closed without merging