Iv thea message handler tests
Polkadex-Substrate/Polkadex pull request #825
Opened 2023-06-27 13:34 UTC by 35359595

## Describe your changes

* thea-message-handler pallet tests, mocks and fixtures shared with benchmarks for consistancy;
* added benchmark for `update_outgoing_nonce` extrinsic;
* generated new Weights on target machine;

## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] I removed all Clippy and Formatting Warnings. 
- [x] I added required Copyrights.

2023-06-29 05:06 UTC, serhii-temchenko approved these changes, later dismissed

2023-06-29 06:21 UTC, Gauthamastro requested changes

2023-06-29 06:21 UTC, Gauthamastro commented on runtime/src/impls.rs
@35359595 Please compare the changes in this file with https://github.com/paritytech/substrate/blob/fe2d51377fe1a8fbbb0599523f4fdc1422c82f81/bin/node/runtime/src/impls.rs#L430

There are certain places where the proof size is not zero. Try to make it the same as the substrate's default test cases.

2023-06-29 09:22 UTC, 35359595 commented on runtime/src/impls.rs
updated with substrate's latest

2023-06-30 07:07 UTC, serhii-temchenko approved these changes

2023-07-03 05:24 UTC, Gauthamastro approved these changes

2023-07-03 05:25 UTC, merged