Fixed benchmarks
Polkadex-Substrate/Polkadex pull request #836
Opened 2023-07-17 13:04 UTC by zktony

## Describe your changes
Fixed benchmarks.

2023-07-19 13:39 UTC, zktony commented
Hey @serhii-temchenko, could you please generate weights?

2023-07-19 17:30 UTC, serhii-temchenko requested changes

2023-07-19 17:30 UTC, serhii-temchenko commented on pallets/thea-executor/src/mock.rs
> +>>>>>>> gj/on-chain-validation
Unresolved conflict

2023-07-19 17:30 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +mod fixtures;
Should be build only for tests/benchmarks only?

2023-07-19 17:30 UTC, serhii-temchenko commented on pallets/thea/src/benchmarking.rs
> -
Please get it back

2023-07-20 03:29 UTC, serhii-temchenko requested changes

2023-07-20 03:29 UTC, serhii-temchenko commented on pallets/thea-message-handler/src/lib.rs
> +mod fixtures;
I assume used only in benchmarks, then should build only for benchmark feature.

2023-07-20 03:29 UTC, serhii-temchenko commented on pallets/thea/src/benchmarking.rs
> +use crate::Pallet as Thea;
Unused?

2023-07-20 03:29 UTC, serhii-temchenko commented on pallets/thea/src/benchmarking.rs
> +impl_benchmark_test_suite!(Thea, crate::mock::new_test_ext(), crate::mock::Test);
Please add empty line at the end of the file.

2023-07-20 03:29 UTC, serhii-temchenko commented on pallets/thea-message-handler/src/fixtures.rs
> +}
Please add empty line at the end of the file.

2023-07-20 03:29 UTC, serhii-temchenko commented on pallets/thea-message-handler/src/benchmarking.rs
> +impl_benchmark_test_suite!(TheaMH, crate::mock::new_test_ext(), crate::mock::Test);
Please add empty line at the end of the file.

2023-07-20 03:29 UTC, serhii-temchenko commented on pallets/ocex/src/fixtures.rs
> +];
Please add empty line at the end of the file.

2023-07-20 03:29 UTC, serhii-temchenko commented on pallets/liquidity/src/mock.rs
> +}
Please add empty line at the end of the file.

2023-07-20 03:33 UTC, serhii-temchenko requested changes

2023-07-20 03:33 UTC, serhii-temchenko commented on pallets/thea-executor/src/benchmarking.rs
> +use crate::{Pallet as TheaExecutor};
Unused?

2023-07-20 03:33 UTC, serhii-temchenko commented on pallets/thea-message-handler/src/benchmarking.rs
> +use crate::{Pallet as TheaMH};
Unused?

2023-07-20 03:33 UTC, serhii-temchenko commented on pallets/thea/src/benchmarking.rs
>  }
Unused

2023-07-20 05:15 UTC, serhii-temchenko commented on pallets/thea/src/benchmarking.rs
> +impl_benchmark_test_suite!(Thea, crate::mock::new_test_ext(), crate::mock::Test);
Fixed

2023-07-20 05:15 UTC, serhii-temchenko commented on pallets/thea-message-handler/src/fixtures.rs
> +}
Fixed

2023-07-20 05:15 UTC, serhii-temchenko commented on pallets/thea-message-handler/src/benchmarking.rs
> +impl_benchmark_test_suite!(TheaMH, crate::mock::new_test_ext(), crate::mock::Test);
Fixed

2023-07-20 05:15 UTC, serhii-temchenko commented on pallets/ocex/src/fixtures.rs
> +];
Fixed

2023-07-20 05:15 UTC, serhii-temchenko commented on pallets/liquidity/src/mock.rs
> +}
Fixed

2023-07-20 06:30 UTC, Gauthamastro commented
Don't merge this, benchmarks is already working in gj/on-chain-validation

2023-07-20 07:04 UTC, serhii-temchenko commented
> Don't merge this, benchmarks is already working in gj/on-chain-validation

Got it.

2023-07-20 07:04 UTC, serhii-temchenko commented
Closed because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/836#issuecomment-1643332941) comment.

2023-07-20 07:04 UTC, closed without merging