Refactored offichain worker code for both Thea and Ocex Pallets
Polkadex-Substrate/Polkadex pull request #863
Opened 2023-08-17 18:07 UTC by zktony

## Describe your changes
Refactored offichain worker code for both Thea and Ocex Pallets.

2023-08-19 19:26 UTC, serhii-temchenko requested changes

2023-08-19 19:26 UTC, serhii-temchenko commented on pallets/ocex/src/aggregator.rs
Please add a module level and all public api (structs and methods) documentation

2023-08-19 19:26 UTC, serhii-temchenko commented on pallets/ocex/src/validator.rs
> +		// Load the next ObMessages¡
What is this change about?

2023-08-19 19:26 UTC, serhii-temchenko commented on pallets/thea/src/aggregator.rs
Please add a module level and all public api (structs and methods) documentation

2023-08-19 19:26 UTC, serhii-temchenko commented on pallets/thea/src/resolver.rs
Please add a module level and all public api (structs and methods) documentation

2023-08-31 06:52 UTC, Gauthamastro requested changes

2023-08-31 06:52 UTC, Gauthamastro commented on pallets/ocex/rpc/src/lib.rs
> +		if !offchain_storage.acquire_offchain_lock(3).await {
Retries must be defined as a constant

2023-08-31 06:52 UTC, Gauthamastro commented on pallets/thea/src/validation.rs
> +				Destination::Solochain,
Resolve the TODO comments

2023-08-31 06:52 UTC, Gauthamastro commented on primitives/orderbook/src/lib.rs
> +			balances: self.balances.clone(),
We can avoid clone by moving self too.

2023-09-01 19:23 UTC, serhii-temchenko requested changes
Please fix the CI errors

2023-09-01 19:23 UTC, serhii-temchenko commented on pallets/ocex/rpc/src/offchain.rs
Please add license and module level documentation

2023-09-01 19:23 UTC, serhii-temchenko commented on pallets/thea/src/aggregator.rs
Please add license and module level documentation

2023-09-01 19:23 UTC, serhii-temchenko commented on pallets/thea/src/resolver.rs
Please add license and module level documentation

2023-09-04 06:37 UTC, Gauthamastro approved these changes

2023-09-04 06:41 UTC, serhii-temchenko approved these changes

2023-09-04 07:10 UTC, merged