Patch: Commented unsafe checker
Polkadex-Substrate/Polkadex pull request #868
Opened 2023-09-07 08:56 UTC by zktony

## Describe your changes
Patch: Commented unsafe checker

2023-09-07 18:30 UTC, serhii-temchenko requested changes

2023-09-07 18:30 UTC, serhii-temchenko commented on primitives/orderbook/src/recovery.rs
> +pub struct DeviationMap {
Please add documentation

2023-09-07 18:30 UTC, serhii-temchenko commented on scripts/check_deviation.sh
> +
Please add `#!/bin/bash` at the beginning

2023-09-07 18:30 UTC, serhii-temchenko commented on pallets/ocex/rpc/src/lib.rs
> +		//self.deny_unsafe.check_if_safe()?;
Why is this commented out? at least, please add some inline comments why it is commented out and not just removed.

2023-09-07 18:30 UTC, serhii-temchenko commented on pallets/ocex/src/validator.rs
> +	//Commting
What is this about?

2023-09-11 06:09 UTC, serhii-temchenko reviewed
CI should be fixed after merge of PR #869.
Will approve after merge of that PR and re-run and success pass of the CI here.

2023-09-11 20:43 UTC, serhii-temchenko approved these changes

2023-09-13 08:11 UTC, Gauthamastro approved these changes

2023-09-13 08:11 UTC, merged