Trading Fees, LMP and much more
Polkadex-Substrate/Polkadex pull request #884
Opened 2023-12-01 06:19 UTC by Gauthamastro

## Issue ticket number and link
Closes https://github.com/Polkadex-Substrate/issue-tracker/issues/261
## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [x] I removed all Clippy and Formatting Warnings. 
- [x] I added required Copyrights.

2023-12-22 11:07 UTC, serhii-temchenko requested changes
Please check and fix the CI

2023-12-22 11:07 UTC, serhii-temchenko commented on Cargo.toml
> +#  "nodes/parachain",
Why parachain was excluded from here?

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +#[frame_support::pallet(dev_mode)]
Is it supposed to be reverted and just missed here?

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +		#[pallet::weight(10_000)]
Weights should be generated?

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +#[frame_support::pallet(dev_mode)]
Is it intentional `dev_mode`?

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +		#[pallet::weight(10000)]
Weights generation?

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +		#[pallet::weight(10000)]
Same

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +		#[pallet::weight(10000)]
Same

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +		#[pallet::weight(10000)]
Same

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
Benchmarks and weights for all extrinsics

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
All todos should be implemented in scope of this PR?

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/types.rs
> +use parity_scale_codec::{Decode, Encode, MaxEncodedLen};
License and copyrights

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/types.rs
> +pub struct MarketMakerConfig<AccountId> {
Please add the dock block

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/callback.rs
> +use crate::pallet::{
Please add the license/copyrights block

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
Please add documentation to the newly added public methods

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
A lot of todos. In scope of which task/pr they should be resolved?

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/ocex/src/lmp.rs
> +use crate::{
Please add license/copyrights block

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/ocex/src/lmp.rs
Please add the documentation for all public functions

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/ocex/src/session.rs
> +use crate::{
Please add license/copyrights block

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/ocex/src/validator.rs
Please add documentation blocks for all public functions

2023-12-22 11:07 UTC, serhii-temchenko commented on primitives/orderbook/src/lmp.rs
> +use sp_std::collections::btree_map::BTreeMap;
Please add license/copyrights block

2023-12-22 11:07 UTC, serhii-temchenko commented on primitives/orderbook/src/traits.rs
> +use frame_support::dispatch::DispatchResult;
Please add license/copyrights block

2023-12-22 11:07 UTC, serhii-temchenko commented on primitives/orderbook/src/traits.rs
Please add documentation for all functions in trait and trait itself

2023-12-22 11:07 UTC, serhii-temchenko commented on pallets/liquidity-mining/Cargo.toml
> +name = "pallet-lmp"
Where this pallet is used? Can't find references...

2023-12-28 03:12 UTC, Gauthamastro commented
@serhii-temchenko @pavankanteti 

@zktony will be testing and implementing the unit tests, resolving comments on this PR.

2024-01-24 06:57 UTC, Gauthamastro commented
resolves https://github.com/Polkadex-Substrate/issue-tracker/issues/268 and https://github.com/Polkadex-Substrate/issue-tracker/issues/267

2024-03-05 12:49 UTC, serhii-temchenko requested changes

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +#[frame_support::pallet(dev_mode)]
Still here? @zktony

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +                // TODO: @zktony Update the verification logic to make it more stringent.
Still here

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +                    .priority(Default::default()) // TODO: update this
Todo still here

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +                    .and_provides("liquidity_mining") // TODO: update this
Todo still here

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +            ); // TODO: @zktony Replace with pool level flags
Should be here?

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +            ); // TODO: @zktony Replace with pool level flags
Should be here?

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +        // maker is expected to call this multiple times to exhaust the pending withdrawals
Still here?

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +            // TODO: Emit events (Ask @frontend team about this)
Still here?

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +            // TODO: Only compute the result every five blocks
Still here?

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +#[frame_support::pallet(dev_mode)]
Still here? @zktony

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +            // Va
?

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/ocex/src/lib.rs
> +        // }
Please remove

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/ocex/src/lmp.rs
> +use crate::{
Still here

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/ocex/src/lmp.rs
Still not everything is covered with docs

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/callback.rs
> +use crate::pallet::{
Copyrights + license Still here

2024-03-05 12:49 UTC, serhii-temchenko commented on pallets/ocex/src/session.rs
> +use crate::{
Copyrights + license Still not resolved

2024-03-05 12:49 UTC, serhii-temchenko commented on primitives/orderbook/src/lmp.rs
Copyrights + license

2024-03-05 12:49 UTC, serhii-temchenko commented on primitives/orderbook/src/traits.rs
> +use frame_support::dispatch::DispatchResult;
Copyrights + license

2024-03-05 15:14 UTC, Gauthamastro commented
@serhii-temchenko Liquidity mining is enabled in this release. It will be a seperate release. You can ignore that for now.

2024-03-06 05:52 UTC, serhii-temchenko approved these changes, later dismissed

2024-03-06 06:46 UTC, serhii-temchenko approved these changes

2024-03-06 06:51 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +            // TODO: Only compute the result every five blocks
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 06:52 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +            // TODO: Emit events (Ask @frontend team about this)
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 06:52 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +        // maker is expected to call this multiple times to exhaust the pending withdrawals
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 06:52 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +            ); // TODO: @zktony Replace with pool level flags
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 06:52 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +            ); // TODO: @zktony Replace with pool level flags
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 06:52 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +                    .and_provides("liquidity_mining") // TODO: update this
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 06:52 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +                    .priority(Default::default()) // TODO: update this
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 06:52 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +                // TODO: @zktony Update the verification logic to make it more stringent.
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 06:53 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
> +#[frame_support::pallet(dev_mode)]
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 06:53 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/lib.rs
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 06:53 UTC, serhii-temchenko commented on pallets/liquidity-mining/src/types.rs
> +pub struct MarketMakerConfig<AccountId> {
Resolving because of [this](https://github.com/Polkadex-Substrate/Polkadex/pull/884#issuecomment-1979004794).

2024-03-06 07:08 UTC, merged