Thea: Fisherman and Batch Signing
Polkadex-Substrate/Polkadex pull request #894
Opened 2024-01-05 05:52 UTC by Gauthamastro

## Describe your changes

This PR raises the final changes to core Thea logic by adding Fisherman model for deposits and batch signing for withdrawals

2024-01-05 05:53 UTC, Gauthamastro commented
@zktony Please add tests for this PR. Let me know if you need any help

2024-01-16 08:06 UTC, serhii-temchenko requested changes

2024-01-16 08:06 UTC, serhii-temchenko commented on pallets/thea-executor/src/lib.rs
> +		pub fn ethereum_withdraw(
No tests for this extrinsic

2024-01-16 08:06 UTC, serhii-temchenko commented on pallets/thea-executor/src/lib.rs
> +		) -> DispatchResult {
Would be nice to have docblock here

2024-01-16 08:06 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +#[frame_support::pallet(dev_mode)]
Should this `dev_mode` be removed?

2024-01-16 08:06 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +				return Err(Error::<T>::NotEnoughStake.into())
Should be tested this condition

2024-01-16 08:06 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +		pub fn submit_signed_outgoing_messages(
It should be tested

2024-01-16 08:06 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +		pub fn report_misbehaviour(
Should be tested

2024-01-16 08:06 UTC, serhii-temchenko commented on pallets/thea/src/lib.rs
> +		pub fn handle_misbehaviour(
Should be tested

2024-01-16 08:06 UTC, serhii-temchenko commented on primitives/thea/src/types.rs
Please add documentation for each new member (pub api) of this file

2024-01-29 19:07 UTC, zktony commented on pallets/thea-executor/src/lib.rs
> +		) -> DispatchResult {
done

2024-01-29 19:08 UTC, zktony commented on pallets/thea-executor/src/lib.rs
> +		pub fn ethereum_withdraw(
Added one test case to test the happy path. Parachain_withdraw tests already cover other cases.

2024-01-31 05:25 UTC, serhii-temchenko requested changes

2024-01-31 05:25 UTC, serhii-temchenko commented on .github/workflows/ci.yml
> +        run: cargo test --workspace
Can this be moved back?

2024-01-31 05:25 UTC, serhii-temchenko commented on pallets/thea-executor/src/mock.rs
> +	// type BenchmarkHelper = AssetU128;
Please remove

2024-01-31 05:25 UTC, serhii-temchenko commented on pallets/thea-message-handler/src/lib.rs
> +		#[pallet::weight(<T as Config>::WeightInfo::incoming_message())] // TODO: @zktony Benchmark again for updated logic
I assume this was updated? Can we remove todo?

2024-01-31 06:38 UTC, Gauthamastro commented
@zktony 

- [ ] on_init in thea
- [ ] paramaterization of on_initialize function in thea 
- [ ] validate_signed_outgoing_message
- [ ] submit_incoming_message
- [ ] match statement inside incoming_message extrinsic in thea message handler.
- [ ] validate_incoming_message in thea message handler ( else blocks are not tested )
- [ ] on_initialize  in thea executor
- [ ] paramaterization of on_initialize function in thea executor
- [ ] add_signature() else condition, contains_signature() methods of SignedMessage in types
- [ ] amount_in_foreign_decimals() method of Deposit type in types.rs

2024-02-01 07:05 UTC, serhii-temchenko approved these changes

2024-02-01 07:10 UTC, zktony approved these changes

2024-02-01 07:10 UTC, merged