Added support for Uncompressed Key
Polkadex-Substrate/Polkadex pull request #910
Opened 2024-02-07 12:01 UTC by zktony

## Describe your changes
Added support for Uncompressed Key.

2024-02-07 12:49 UTC, Gauthamastro submitted a review, later dismissed

2024-02-07 12:49 UTC, Gauthamastro commented on pallets/thea/src/lib.rs
> +					log::error!(target: "thea", "Unable to parse compressed key");
Emit an event here.

2024-02-12 11:03 UTC, Gauthamastro requested changes

2024-02-12 11:03 UTC, Gauthamastro commented on pallets/thea/src/tests.rs
> +			key_type: NetworkType::Parachain,
Rename parameter

2024-02-12 11:03 UTC, Gauthamastro commented on pallets/thea/src/tests.rs
> +			key_type: NetworkType::Parachain,
Rename parameter

2024-02-12 11:03 UTC, Gauthamastro commented on pallets/thea/src/tests.rs
> +			key_type: NetworkType::Parachain,
same

2024-02-12 11:37 UTC, zktony commented on pallets/thea/src/tests.rs
> +			key_type: NetworkType::Parachain,
done

2024-02-12 13:29 UTC, Gauthamastro approved these changes

2024-02-12 13:54 UTC, serhii-temchenko approved these changes

2024-02-12 17:06 UTC, merged