Extended XCM Test Cases
Polkadex-Substrate/Polkadex pull request #962
Opened 2024-05-29 20:35 UTC by zktony

## Describe your changes
Extended XCM Test Cases.

2024-05-30 07:21 UTC, Gauthamastro requested changes
@zktony Where are the test cases in simulator for sending PDEX from mainnet to parachain

2024-05-30 07:21 UTC, Gauthamastro commented on pallets/xcm-helper/src/lib.rs
> +					log::error!(target:"xcm-helper","Deposit Failed");
Deposit a failure event here

2024-05-30 07:21 UTC, Gauthamastro commented on pallets/xcm-helper/src/lib.rs
> +			// Self::resolve_transfer(asset_id.into(), &from, &to, amount)
Remove comments

2024-05-30 07:21 UTC, Gauthamastro commented on pallets/xcm-helper/src/lib.rs
> +			//panic!("Transfer is called from {:?} to {:?} with asset {:?}", from, to, asset);
Same here

2024-05-30 07:21 UTC, Gauthamastro commented on pallets/xcm-helper/src/lib.rs
> -										log::error!(target:"xcm-helper","Withdrawal failed: Not able to make xcm calls");
Deposit failure event

2024-05-30 07:21 UTC, Gauthamastro commented on pallets/xcm-helper/src/lib.rs
> +										log::error!(target:"xcm-helper","Withdrawal failed: Not able to decode destination");
Deposit event

2024-05-30 07:21 UTC, Gauthamastro commented on pallets/xcm-helper/src/lib.rs
> +										failed_withdrawal.push(withdrawal.clone());
Failure event here

2024-05-30 07:21 UTC, Gauthamastro commented on pallets/xcm-helper/src/lib.rs
>  									log::error!(target:"xcm-helper","Withdrawal failed: Not able to mint token");
Failure event here

2024-05-30 07:21 UTC, Gauthamastro commented on pallets/xcm-helper/src/lib.rs
> -									log::error!(target:"xcm-helper","Withdrawal failed: Not able to make xcm calls");
Failure event here

2024-05-30 07:21 UTC, Gauthamastro commented on pallets/xcm-helper/src/lib.rs
> +								log::error!(target:"xcm-helper","Withdrawal failed: Not able to handle dest");
Failure event here

2024-05-30 07:21 UTC, Gauthamastro commented on pallets/xcm-helper/src/lib.rs
> +											log::error!(target:"xcm-helper","Withdrawal failed: Not able to decode destination");
Failure event here

2024-05-30 07:21 UTC, Gauthamastro commented on polkadex-xcm-simulator/Cargo.toml
> +#polkadot-runtime-common = { workspace = true, default-features = false }
Remove this

2024-05-30 11:06 UTC, zktony commented
> @zktony Where are the test cases in simulator for sending PDEX from mainnet to parachain
https://github.com/Polkadex-Substrate/Polkadex/blob/95832aa4bfe9aeb7a498d8edff29b9ef20e7315e/polkadex-xcm-simulator/src/lib.rs#L524

2024-05-30 11:32 UTC, Gauthamastro commented
> > @zktony Where are the test cases in simulator for sending PDEX from mainnet to parachain
> > https://github.com/Polkadex-Substrate/Polkadex/blob/95832aa4bfe9aeb7a498d8edff29b9ef20e7315e/polkadex-xcm-simulator/src/lib.rs#L524

Update the name, from non-native to native. Its misleading

2024-05-30 19:28 UTC, serhii-temchenko requested changes

2024-05-30 19:28 UTC, serhii-temchenko commented on pallets/xcm-helper/src/lib.rs
> +					log::error!(target:"xcm-helper","Deposit Failed");
Still not resolved.

2024-05-30 19:28 UTC, serhii-temchenko commented on pallets/xcm-helper/src/lib.rs
> +										failed_withdrawal.push(withdrawal.clone());
Still not resolved.

2024-05-31 03:56 UTC, Gauthamastro requested changes
Two failure events are missing

2024-05-31 10:32 UTC, Gauthamastro approved these changes

2024-05-31 10:39 UTC, serhii-temchenko approved these changes

2024-05-31 10:40 UTC, merged